# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MorningStar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftSVG'
pod 'SnapKit'
pod 'Spring', :git => 'https://github.com/MussaCharles/Spring.git'
pod 'Pastel'
pod 'Parse'
pod 'ParseLiveQuery'
# Pods for MorningStar

end
